services:
  postgres:
    image: postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
    restart: always
    container_name: creme
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - target: 5432
        published: ${HOST_PORT}
        protocol: tcp
        mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres_data:
    driver: local
